BEGIN;
DROP TABLE IF EXISTS public.overlay_policy_reconcile_pending;
DROP TABLE IF EXISTS public.overlay_gateway_apply_attempts;
ALTER TABLE public.overlay_policy_builds DROP COLUMN IF EXISTS artifact_canonical;
ALTER TABLE public.overlay_policy_revisions DROP COLUMN IF EXISTS artifact_canonical;
ALTER TABLE public.overlay_gateway_apply_results DROP CONSTRAINT IF EXISTS overlay_gateway_apply_results_semantics_ck;
ALTER TABLE public.overlay_gateway_apply_results DROP CONSTRAINT IF EXISTS overlay_gateway_apply_results_generation_ck;
ALTER TABLE public.overlay_gateway_apply_results DROP CONSTRAINT IF EXISTS overlay_gateway_apply_results_result_check;
ALTER TABLE public.overlay_gateway_apply_results ADD CONSTRAINT overlay_gateway_apply_results_applied_generation_check CHECK(applied_generation=0);
ALTER TABLE public.overlay_gateway_apply_results ADD CONSTRAINT overlay_gateway_apply_results_runtime_applied_check CHECK(runtime_applied=FALSE);
ALTER TABLE public.overlay_gateway_apply_results ADD CONSTRAINT overlay_gateway_apply_results_result_check CHECK(result IN ('shadow_validated','shadow_validated_wg_unavailable','shadow_rejected'));
ALTER TABLE public.overlay_gateway_node_status DROP CONSTRAINT IF EXISTS overlay_gateway_node_status_generation_ck;
ALTER TABLE public.overlay_gateway_node_status DROP CONSTRAINT IF EXISTS overlay_gateway_node_status_mode_check;
ALTER TABLE public.overlay_gateway_node_status ADD CONSTRAINT overlay_gateway_node_status_mode_check CHECK(mode='shadow');
ALTER TABLE public.overlay_gateway_node_status ADD CONSTRAINT overlay_gateway_node_status_applied_generation_check CHECK(applied_generation=0);
ALTER TABLE public.overlay_nodes DROP COLUMN IF EXISTS gateway_mode;
DROP TABLE IF EXISTS public.overlay_device_events;
DROP INDEX IF EXISTS public.overlay_devices_network_active_public_key_uk;
CREATE UNIQUE INDEX overlay_devices_network_public_key_uk ON public.overlay_devices(network_id,wireguard_public_key);
ALTER TABLE public.overlay_devices DROP CONSTRAINT IF EXISTS overlay_devices_revoked_state_ck;
ALTER TABLE public.overlay_devices DROP COLUMN IF EXISTS revoked_reason;
ALTER TABLE public.overlay_devices DROP COLUMN IF EXISTS revoked_at;
ALTER TABLE public.overlay_devices DROP COLUMN IF EXISTS key_version;
ALTER TABLE public.overlay_devices DROP COLUMN IF EXISTS state_version;
ALTER TABLE public.overlay_devices DROP COLUMN IF EXISTS status;
COMMIT;
