service_compose_env_common:
  CONFIG_TEMPLATE: /app/config/account.cloudrun.yaml
  DB_TLS_HOST: postgresql-aws.svc.plus
  DB_TLS_PORT: "5443"
  POSTGRES_USER: postgres
  DB_USER: postgres
  DB_NAME: account
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_FROM: "XWorkmate <no-reply@xworktech.com>"
  SMTP_USERNAME: no-reply@xworktech.com
